export const timelineProperties = [
  { label: "Character Model URL", path: "character.modelUrl" },
  { label: "Character Animation Clip", path: "character.animationClip" },
  { label: "Character Position", path: "character.position" },
  { label: "Character Rotation", path: "character.rotation" },
  { label: "Character Scale", path: "character.scale" },
  { label: "Character Animation Mode", path: "character.animation" },
  { label: "Character Animation Speed", path: "character.animationSpeed" },
  { label: "Character Auto Rotate", path: "character.autoRotate" },
  { label: "Camera Position", path: "camera.position" },
  { label: "Camera FOV", path: "camera.fov" },
  { label: "Camera Target", path: "camera.target" },
  { label: "Light Key Color", path: "lighting.keyColor" },
  { label: "Light Key Intensity", path: "lighting.keyIntensity" },
  { label: "Light Rim Color", path: "lighting.rimColor" },
  { label: "Light Rim Intensity", path: "lighting.rimIntensity" },
  { label: "Light Accent Color", path: "lighting.accentColor" },
  { label: "Light Accent Intensity", path: "lighting.accentIntensity" },
  { label: "Energy Ring Color", path: "effects.energyRingColor" },
  { label: "Bloom Intensity", path: "effects.bloomIntensity" },
  { label: "Energy Ring Speed", path: "effects.energyRingSpeed" },
  { label: "Particle Color", path: "effects.particleColor" },
  { label: "Particle Count", path: "effects.particleCount" },
  { label: "Vignette Darkness", path: "effects.vignetteDarkness" },
  { label: "Debug Grid", path: "debug.showGrid" },
  { label: "Debug Axes", path: "debug.showAxes" },
  { label: "Debug Helpers", path: "debug.showHelpers" },
] as const;
